### ISSUE TITLE
New test for legacy privacy transactions

### ISSUE THREAD

**Issue by siladu** [Consensys/PEEPS#87]
Add a privacy test using legacy privateFrom instead of privacy groups.

**Acceptance Criteria**
- Test that submits a private transaction deploying a contract without privacy groups similar to the existing PrivacyContractDeploymentTest.
- Test must use EthSigner, Besu and Tessera

**Comment by macfarla** [comment]
Orion will be deprecated as of end of Nov (tomorrow!) so no need to add new tests for it
