### ISSUE TITLE
Besu IBFT1 no longer syncs with GoQuorum

### ISSUE THREAD

**Issue by jframe** [ConsenSys/PEEPS#95]
The IBFT1 test checks that Besu can sync a IBFT 1 chain with GoQuorum and relay transactions is no longer passing after the latest GoQuorum update.

This is an example of the test failure

https://app.circleci.com/pipelines/github/ConsenSys/PEEPS/655/workflows/fa17ffb2-8e01-46f4-acb6-3fca53999a0e/jobs/1669/tests

note: The test is temporarily ignored whilst this is under investigation

**Comment by lucassaldanha** [comment]
Moved to https://github.com/hyperledger/besu/issues/3387
